name: Create Terraform Resources

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: Grupo-118-Desafio-Final/final-challenge-grupo-118-template-pipeline/.github/workflows/terraform-template-creation-resource.yml@main
    secrets: inherit
